pipeline {
    agent any {
        stages {
            stage('Checkout') {
                steps {
                    echo 'Checking out code...'
                    checkout scm
                }
            }
            stage('Install Dependencies') {
                steps {
                    sh '''
                    python3 -m venv venv
                    source venv/bin/activate
                    echo 'Installing dependencies...'
                    pip install -r requirements.txt
                    '''
                }
            }
            stage('Test') {
                steps {
                    sh '''
                        . venv/bin/activate
                        python3 manage.py test
                    '''

                }
            }
            stage('Build') {
                steps {
                    sh '''
                        echo "Building Docker image..."

                        docker build -t myapp:latest .

                        docker tag myapp:latest pratikkamble14/myapp:latest

                        echo "Stopping old containers..."
                        docker compose down

                        echo "Starting new containers..."
                        docker compose up -d

                        echo "Checking containers..."
                        docker compose ps
                    '''
                }
            }
        }
    }
}